hometask 2 css
ok-technopolis-autumn-2019/Ilya_Gusarov pull request #2
Opened 2019-11-03 16:53 UTC by gogun

2019-11-04 12:53 UTC, fromanywhere requested changes

2019-11-04 12:53 UTC, fromanywhere commented on index.html
> +            <input class="todo-display-edit__filter__input" type="radio" name="filter" role="radio" value="All" aria-label="display-all">
Нейминг не по бэм

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +header {
Не, у нас уже бэм, никаких селекторов по тэгу

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    letter-spacing: -2.5px;
не надо таким заниматься

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +  .upper-menu-bar .select-all {
Есть ли смысл в каскаде здесь и ниже?

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    flex:4;
почему 4?

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    width: 40px;
Прилипло к левому краю 
![image](https://user-images.githubusercontent.com/1042969/68121797-b6580d80-ff19-11e9-91f3-665b35ddbc8b.png)

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    background-image: url("icons/checked_1.svg"), url("icons/checked_2.svg");
Очень интересное решение с двойным бэкграундом, но оно вам испортит жизнь, когда я попрошу (а я попрошу) дорисовать состояние обводки на фокус, потому что сейчас при клавиатурной навигации реально неясно, где я нахожусь. Сделайте лучше обводку бордером и перекрашивайте его

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    visibility: visible;
с клавиатуры тяжеловато сюда попасть, подумайте про состояние на фокус

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    flex: 0.5;
я не думаю, что это действительно нужно в наших простых кейсах

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    visibility: hidden;
не зафокусится же

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    line-height: 21px;
Порвало 
![image](https://user-images.githubusercontent.com/1042969/68122021-6cbbf280-ff1a-11e9-9247-d0016f8fec58.png)

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +  height: 64px;
Не думаю, что фиксировать высоту — хорошая идея

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +    padding-right: 12px;
Цвет слетел 
![image](https://user-images.githubusercontent.com/1042969/68122116-aee53400-ff1a-11e9-9ee4-95bde7d93da9.png)

2019-11-04 12:53 UTC, fromanywhere commented on style.css
> +  font-family: "Roboto", sans-serif;
А где сам шрифт подключается?

2019-11-04 13:07 UTC, gogun commented on style.css
> +    width: 40px;
Вроде бы поправил это последним коммитом
![изображение](https://user-images.githubusercontent.com/17166741/68123126-27e58b00-ff1d-11e9-9eef-d8aedeb2e1c4.png)

2019-11-04 13:48 UTC, gogun commented on style.css
> +    width: 40px;
не запушил)

2019-11-04 13:51 UTC, gogun commented on style.css
> +    background-image: url("icons/checked_1.svg"), url("icons/checked_2.svg");
Добавил фокус на двойной бекгрунд, все работает вроде как

2019-11-04 14:24 UTC, gogun commented on style.css
> +    visibility: hidden;
Вроде фокусится...

2019-11-04 18:48 UTC, fromanywhere commented
Ну потрясающе, теперь не только фокус исключительно на ховере заметен, а вообще все действия на элементе 
![image](https://user-images.githubusercontent.com/1042969/68148317-cb9a5f80-ff4c-11e9-8787-7075b5247c6c.png)
Вот Вам референс https://welovehtml.ru/dev/todo/

2019-11-04 21:10 UTC, gogun commented
как-то странно в этом референсе появляется зеленая обводка (firefox 70)

2019-11-04 22:03 UTC, gogun commented
Вроде всё поправил, в соответствии с референсом

2019-11-04 22:14 UTC, fromanywhere commented
> Вроде всё поправил, в соответствии с референсом

Да ну нет же. Вот пройдитесь табом по контролам и попробуйте угадать, что будет, если пробел нажать. 

Ну или вот я скринкаст записал — сможете по нему угадать, какие клавиши и в каком порядке я нажимаю? 
![screencast 2019-11-05 01-12-22](https://user-images.githubusercontent.com/1042969/68162676-a23bfc80-ff69-11e9-903b-95375655cd3b.gif)

2019-11-05 00:16 UTC, gogun commented
так больше похоже на правду?

2019-11-05 05:19 UTC, fromanywhere commented
> так больше похоже на правду?

Почти получилось, но .todo-display-edit__filter-input не принимает фокус из-за display: none, клавиатурой до фильтров не добраться

2019-11-05 09:36 UTC, gogun commented
Поправил

2019-11-05 10:29 UTC, fromanywhere approved these changes

2019-11-05 13:09 UTC, merged